# Generated by Django 6.0.7 on 2026-08-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='target_class',
            field=models.CharField(default='2IA06', help_text='Kelas yang wajib ikut, contoh: 2IA06', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule', 'user')},
        ),
    ]
