# Generated by Django 6.0.7 on 2026-08-16 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_target_class_alter_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Tulis pertanyaan ringkas dan jelas', max_length=255)),
                ('answer', models.TextField(help_text='Jawaban lengkap')),
                ('order', models.PositiveIntegerField(default=0, help_text='Prioritas urutan tampil (contoh: 1, 2, 3)')),
                ('is_active', models.BooleanField(default=True, help_text='Centang untuk menampilkan website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Daftar FAQ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('schedule', 'user'), name='unique_schedule_user'),
        ),
    ]
