# Generated by Django 6.0.7 on 2026-08-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_faq_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
