# Generated by Django 6.0.7 on 2026-08-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_assistant_id_customuser_npm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kelas',
            field=models.CharField(blank=True, help_text='Contoh: 2IA06', max_length=10),
        ),
    ]
