# Generated by Django 6.0.7 on 2026-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assistant_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='npm',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PRAKTIKAN', 'Praktikan'), ('ASISTEN', 'Asisten')], default='PRAKTIKAN', max_length=20),
        ),
    ]
